sync-with-github:
  tags: 
    - linux
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - git push https://$UNAME:$PASSWD@github.com/5trubel/strubel-lgsm.git HEAD:master
