sync-with-github:
  tags: 
    - linux
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - git remote add origin https://github.com/5trubel/strubel-lgsm.git
    - git branch -M main
    - git push https://$UNAME:$PASSWD@github.com/5trubel/strubel-lgsm.git main
